### ISSUE TITLE
Implement secrets method of authorisation

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/outlook#35]
Implement secrets method of authorisation for this component.

**Comment by andrewreshitko** [comment]
The current AUTH method - is not clear how to setup credentials
![image](https://github.com/elasticio/outlook/assets/110159769/b46c3b2f-90fc-4687-a9e5-bbf4184c92a7)

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/outlook/releases/tag/2.0.0
